### PR TITLE
fix: image validation added, req.body validation updated

### LINKED ISSUE #58: Validation Bugs
- The body shouldn't expect/see the fields that were not set at the validators. [This ](https://github.com/express-validator/express-validator/issues/809)might help
- When you upload more than maximum allowed images, it gives "Unexpected field"
- Should validate images, only allow specific image types. `jpeg|jpg|png`

### PR DESCRIPTION
**Pull request by cbaksakal**
Fixes #58

### CODE REVIEW

File: src/routes/products.js [hunk 1]
```diff
@@ -44,7 +70,9 @@ router.post(
     body('type')
       .not()
       .isEmpty()
-      .withMessage('Please select the type of the product!'),
+      .withMessage('Type cannot be empty!')
+      .isIn(['Product', 'Service'])
```
Comment (muslimomar) [inline src/routes/products.js:74]: Good catch here!

**Review by muslimomar — APPROVED** [review]
